version: '3.8'

services:
  self-key:
    image: postgres:15
    container_name: self-key
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: selfkey_db
    ports:
      - "5432:5432"
    volumes:
      - selfkey_data:/var/lib/postgresql/data

volumes:
  selfkey_data:
